name: going_home_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.1.0
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_remote_config: ^3.0.6
  firebase_dynamic_links: ^5.0.7
  firebase_messaging: ^14.1.3

  # State Management
  json_annotation: ^4.7.0
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  freezed: ^2.3.0
  freezed_annotation: ^2.2.0
  flutter_state_notifier: ^0.7.1
  json_serializable: ^6.5.4

  # other
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  grinder: ^0.9.2
  package_info_plus: ^3.0.2
  google_fonts: ^3.0.1
  analyzer: ^5.2.0
  location: ^5.0.0-dev.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_flavorizr: ^2.1.5
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: 'flavor-type'
    ios:

  flavors:
    dev:
      app:
        name: 'going_home_app_dev'

      android:
        applicationId: 'going_home.app.dev'

      ios:
        bundleId: 'going_home.app.dev'

    prod:
      app:
        name: 'going_home_app_prod'

      android:
        applicationId: 'going_home.app.prod'

      ios:
        bundleId: 'going_home.app.prod'
