// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrRKsjLgeERYluxvipnaoBAkn26jE2kXY',
    appId: '1:168611388654:web:117ebcaf74c70ae52227ff',
    messagingSenderId: '168611388654',
    projectId: 'going-home-a47ce',
    authDomain: 'going-home-a47ce.firebaseapp.com',
    storageBucket: 'going-home-a47ce.appspot.com',
    measurementId: 'G-K22F29HTEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2NMzjwNaQ1MfpiQzJRqYj0j6BJy15vl4',
    appId: '1:168611388654:android:f1d7bf2ad40348d42227ff',
    messagingSenderId: '168611388654',
    projectId: 'going-home-a47ce',
    storageBucket: 'going-home-a47ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYHFVsf9Eeq8zTi-BCpUtqjU2PV81xw1I',
    appId: '1:168611388654:ios:e4ed59ae8c180d592227ff',
    messagingSenderId: '168611388654',
    projectId: 'going-home-a47ce',
    storageBucket: 'going-home-a47ce.appspot.com',
    iosClientId: '168611388654-0i1orcosviaj3h1m6u2nds3p0s6n5c0b.apps.googleusercontent.com',
    iosBundleId: 'com.mine2424.goingHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYHFVsf9Eeq8zTi-BCpUtqjU2PV81xw1I',
    appId: '1:168611388654:ios:e4ed59ae8c180d592227ff',
    messagingSenderId: '168611388654',
    projectId: 'going-home-a47ce',
    storageBucket: 'going-home-a47ce.appspot.com',
    iosClientId: '168611388654-0i1orcosviaj3h1m6u2nds3p0s6n5c0b.apps.googleusercontent.com',
    iosBundleId: 'com.mine2424.goingHomeApp',
  );
}
